=== Genis-01/marcas/xsd/xsd II/ejercicio1/xsd.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ficha">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alubno" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="nota-primer-trimestre" type="nota"/>
                            <xs:element name="nota-segundo-trimestre" type="nota"/>
                            <xs:element name="nota-tercer-trimestre" type="nota"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="nota">
        <xs:restriction base="xs:integer">
            <xs:maxInclusive value="10"></xs:maxInclusive>
            <xs:minInclusive value="0"></xs:minInclusive>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Genis-01/marcas/xsd/xsd II/ejercicio1/xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<ficha xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd.xsd">
    <alubno>
        <nombre>Pedro</nombre>
        <nota-primer-trimestre>4</nota-primer-trimestre>
        <nota-segundo-trimestre>6</nota-segundo-trimestre>
        <nota-tercer-trimestre>8</nota-tercer-trimestre>
    </alubno>
    <alubno>
        <nombre>toni</nombre>
        <nota-primer-trimestre>8</nota-primer-trimestre>
        <nota-segundo-trimestre>7</nota-segundo-trimestre>
        <nota-tercer-trimestre>5</nota-tercer-trimestre>
    </alubno>
</ficha>
